spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/school?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true&allowPublicKeyRetrieval=true
    username: root
    password: tiger
    driver-class-name: com.mysql.jdbc.Driver