server:
  port: 9080
  compression:
    enabled: true
    min-response-size: 1024
    mime-types: application/javascript,application/json,application/xml,text/html,text/xml,text/plain,text/css,image/*

spring:
  profiles:
    active: mysql
  application:
    name: chat
  config:
    import:
      - classpath:s2-config.yaml
  autoconfigure:
    exclude:
      - spring.dev.langchain4j.spring.LangChain4jAutoConfig
      - spring.dev.langchain4j.openai.spring.AutoConfig
      - spring.dev.langchain4j.ollama.spring.AutoConfig
      - spring.dev.langchain4j.azure.openai.spring.AutoConfig
      - spring.dev.langchain4j.azure.aisearch.spring.AutoConfig
      - spring.dev.langchain4j.anthropic.spring.AutoConfig
  main:
    allow-circular-references: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

mybatis:
  mapper-locations=classpath:mappers/custom/*.xml,classpath*:/mappers/*.xml

logging:
  level:
    dev.langchain4j: DEBUG
    dev.ai4j.openai4j: DEBUG

swagger:
  title: 'SuperSonic API Documentation'
  base:
    package: com.tencent.supersonic
  description: 'SuperSonic API Documentation'
  url: ''
  contact:
    name:
    email:
    url: ''
  version: 3.0